# Generated by Django 4.2.1 on 2023-05-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0003_alter_producto_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='respuesta',
            new_name='nombre',
        ),
    ]
