# Generated by Django 4.2.1 on 2023-05-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0004_rename_respuesta_pregunta_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='respuesta',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
