# Generated by Django 4.2.1 on 2023-05-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0005_usuario_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='respuesta',
            field=models.CharField(max_length=220),
        ),
    ]
